source.dir("fun/data")
source.dir("fun/html")
source.dir("fun/stat")
source.dir("fun/tour")
.specialNames <- read.delim('data/specialNames.txt', header=FALSE, stringsAsFactors=FALSE)
.fixNames <- read.delim('data/fixNames.txt', header=FALSE, stringsAsFactors=FALSE)
