#!/usr/bin/env Rscript
suppressMessages(library(docopt))
"Usage: fit <side> <year> [-h]

--<side>  atp/wta
--<year>  2012/2013/...
-h        Show this help screen" -> doc
opt <- docopt(doc)
side <- opt$side
year <- as.numeric(opt$year)
# side <- "atp"
# year <- 2015

# Import
Data <- import(year, side)
df <- Data$Data
y <- df$Wsets
ns <- df$Wsets + df$Lsets
nm <- nrow(df)
np <- length(Data$PlayerID)
prior <- makePrior(Data$PlayerID, side, year)

# Fit setup
jData <- with(Data, list(
  Winner=Winner, Loser=Loser, Surface=Surface, Time=Time, T=max(Time), y=y, ns=ns, nm=nm, np=np))
jData <- c(jData, prior)
monitor <- c("eta", "alpha", "tau")
FUN <- function(chain) {list(eta=matrix(rnorm(np*max(Data$Time)), nrow=np), alpha=matrix(rnorm(np*3), nrow=np))}
inits <- mapply(FUN, 1:3, SIMPLIFY=FALSE)

# Fit
require(runjags)
runjags.options(rng.warning=FALSE)
jagsfit <- run.jags("fun/stat/model.txt", monitor=monitor, data=jData, inits=inits, n.chains=length(inits),
                    method="rjparallel", adapt = 500, burnin=500, sample=2000, summarise=FALSE)

# Summarize & Save
fit <- convert(jagsfit)
R2WinBUGS:::attach.bugs(fit)

Eta <- apply(eta, 2:3, mean)
rownames(Eta) <- Data$PlayerID
colnames(Eta) <- Data$TimeID
Delta <- Eta[,ncol(Eta)]
Alpha <- apply(alpha, 2:3, mean)
rownames(Alpha) <- Data$PlayerID
colnames(Alpha) <- Data$SurfaceID

sdEta <- apply(eta, 2:3, sd)
rownames(sdEta) <- Data$PlayerID
colnames(sdEta) <- Data$TimeID
sdAlpha <- apply(alpha, 2:3, sd)
rownames(sdAlpha) <- Data$PlayerID
colnames(sdAlpha) <- Data$SurfaceID

m <- apply(tau, 2, mean)
v <- apply(tau, 2, var)
rss <- 2*m/v
tdf <- rss*m

save(Eta, Alpha, Delta, sdEta, sdAlpha, rss, tdf, file=paste0("psm/", side, "/", year, ".RData"))
