#!/usr/bin/env Rscript
suppressMessages(library(docopt))
"Usage: fit <side> <year> [-h]

--<side>  atp/wta
--<year>  2012/2013/...
-h        Show this help screen" -> doc
opt <- docopt(doc)
side <- opt$side
year <- as.numeric(opt$year)
# side <- "atp"
# year <- 2012:2016

## Import
Data <- import(year, side)
df <- Data$Data
y <- df$Wsets
ns <- df$Wsets + df$Lsets
nm <- nrow(df)
np <- length(Data$PlayerID)

## Fit setup
jData <- with(Data, list(Winner=Winner, Loser=Loser, Surface=Surface, Time=Time, T=max(Time), y=y, ns=ns, nm=nm, np=np))
monitor <- c("eta", "alpha", "sigma")
FUN <- function(chain) {list(eta=matrix(rnorm(np*max(Data$Time)), nrow=np), alpha=matrix(rnorm(np*3), nrow=np))}
inits <- mapply(FUN, 1:3, SIMPLIFY=FALSE)

## Fit
require(runjags)
runjags.options(rng.warning=FALSE)
jagsfit <- run.jags("fun/stat/model.txt", monitor=monitor, data=jData, inits=inits, n.chains=length(inits),
                    method="rjparallel", adapt = 1000, burnin=1000, sample=2000, summarise=FALSE)

## Summarize & Save
fit <- convert(jagsfit)
R2WinBUGS:::attach.bugs(fit)

Eta <- apply(eta, 2:3, mean)
rownames(Eta) <- Data$PlayerID
colnames(Eta) <- Data$TimeID
Delta <- Eta[,ncol(Eta)]
Alpha <- apply(alpha, 2:3, mean)
rownames(Alpha) <- Data$PlayerID
colnames(Alpha) <- Data$SurfaceID
Sigma <- apply(sigma, 2, mean)

sdEta <- apply(eta, 2:3, sd)
rownames(sdEta) <- Data$PlayerID
colnames(sdEta) <- Data$TimeID
sdAlpha <- apply(alpha, 2:3, sd)
rownames(sdAlpha) <- Data$PlayerID
colnames(sdAlpha) <- Data$SurfaceID
sdSigma <- apply(sigma, 2, sd)

save(Eta, Alpha, Delta, Sigma, sdEta, sdAlpha, sdSigma, file=paste0("psm/", side, "/", year, ".RData"))
