#!/bin/bash
DATE=$(date +%Y-%m-%d)
echo "---" >> _posts/$DATE-$1.md
echo "title: $1" >> _posts/$DATE-$1.md
echo "---" >> _posts/$DATE-$1.md
echo "{% include_relative tab/table.html %}" >> _posts/$DATE-$1.md
emacs _posts/$DATE-$1.md
